version: "3.9"

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        REACT_APP_STOCK_QUOTE_BASE_URL: "<>"
        REACT_APP_STOCK_CONTEST_BASE_URL: "<>"
    container_name: stock-client
    restart: on-failure
    ports:
      - "80:80"

networks:
  default:
    external: true
    name: stock-analyzer_default