version: "3.9"

services:
  next:
    container_name: stockcomp-client
    build:
      context: "."
      dockerfile: "Dockerfile"
    ports:
      - "3000:3000"

networks:
  default:
      name: compose_network
      external: true