apiVersion: skaffold/v4beta1
kind: Config
build:
  artifacts:
    - image: stockcomp-client-image
      sync:
        infer:
          - '**/*.ts'
          - '**/*.tsx'
          - '**/*.js'
          - '**/*.jsx'
          - '**/*.css'
portForward:
  - resourceType: deployment
    resourceName: stockcomp-client-deployment
    port: 3000