apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: stockcomp-client

build:
  artifacts:
  - image: stockcomp-client-image
    sync: #File sync for copying changed files to a deployed container, to avoid rebuild and redeploy pod
      infer: #The destination for each changed files
        - '**/*.ts'
        - '**/*.tsx'
        - '**/*.js'
        - '**/*.jsx'
        - '**/*.css'

manifests:
  rawYaml:
    - k8s/stockcomp-client.yaml
    - k8s/oauth2-proxy.yaml

deploy:
  kubectl: {}
