apiVersion: apps/v1
kind: Deployment
metadata:
  name: stockcomp-client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stockcomp-client
  template:
    metadata:
      labels:
        app: stockcomp-client
    spec:
      containers:
        - name: stockcomp-client
          image: stockcomp-client-image
          ports:
            - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: stockcomp-client-service
spec:
  selector:
    app: stockcomp-client
  ports:
    - port: 80
      targetPort: 3000

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stockcomp-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: stockcomp.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: stockcomp-client-service
                port:
                  number: 80
          - path: /api/.*
            pathType: Prefix
            backend:
              service:
                name: stockcomp-client-backend-service
                port:
                  number: 80