name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  STOCK_QUOTE_URL_ARG: REACT_APP_STOCK_QUOTE_BASE_URL=http://stock-analyzer:8088
  STOCK_CONTEST_URL_ARG: REACT_APP_STOCK_CONTEST_BASE_URL=http://stockcomp-service:8080

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14.18.0

      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: stockclient
          tags: latest
          dockerfile: Dockerfile.prod
          buildArgs: ${{ env.STOCK_QUOTE_URL_ARG }}, ${{ env.STOCK_CONTEST_URL_ARG }}
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}